-- 코드를 작성해주세요
SELECT ID, IF(SIZE_OF_COLONY<=100,'LOW',
             IF(SIZE_OF_COLONY<=1000,'MEDIUM','HIGH')) AS SIZE

FROM ECOLI_DATA
ORDER BY ID ASC;
/*SELECT ID, SIZE
FROM ECOLI_DATA
WHERE SIZE_OF_COLONY < 100 THEN 'LOW' 
AND SIZE_OF_COLONY BETWEEN 100 AND 1000 THEN 'MEDIUM'
AND SIZE_OF_COLONY > 1000 THEN "HIGH"
AS SIZE
*/